v3.25.70 (#4807)
* Fix inclusive issue for z.size and z.length checks

* Run lib check in resolution tests

* Docs fixes

* Relax mask, remove util.Exactly. Closes #4797

* Drop ref to Error.captureStackTrace. Fixes #4786

* Export z.NEVER from mini. Closes #4796

* Throw informative error when non-POJO passed into .extend(). Closes #4793

* Minimize use of destructuring. Closes #4773

* Remove unused decl

* Check for untracked prepush

* Update untracked files check

* Update untracked files check

* Update precommit

* 3.25.70

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,9 @@
-pnpm test
+if [ -n "$(git ls-files --others --exclude-standard)" ]; then
+  echo "ERROR: untracked files present"; 
+  git status;
+  exit 1
+fi
 pnpm semver-check
+pnpm test
 pnpm build
 pnpm clean
